### ISSUE TITLE
publish app to F-Droid

### ISSUE THREAD

**Issue by davidak** [mapswipe/yourmapswipe-react-native-app#1]
[F-Droid](https://f-droid.org) is an android app store for free and open source software.

It would be nice to have your app there, so people who don't want to have google play store on their phone can use it.

**Comment by PimDeWitte** [comment]
I added a direct APK download opton: https://drive.google.com/drive/u/0/folders/0BwsMM5hElkXEYnN0eWNVT0dFU00

**Comment by davidak** [comment]
Thanks. What is the SHA256-Hash of the file?

Closing this issue means you don't want to support F-Droid?

**Comment by Rudloff** [comment]
Hello,
I would also be interested in having this app in F-Droid.
@PimDeWitte Would you be OK if the app was added to F-Droid repositories?

**Comment by PimDeWitte** [comment]
Go for it. Apk is on the website

Pim de Witte
+1 786 201 9489 <+1%20786%20201%209489>
CEO, Ferox


On Aug 1, 2017 at 8:52 AM, Pierre Rudloff <notifications@github.com> wrote:


Hello,
I would also be interested in having this app in F-Droid.
@PimDeWitte <https://github.com/pimdewitte> Would you be OK if the app was
added to F-Droid repositories?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mapswipe/yourmapswipe-react-native-app/issues/1#issuecomment-319413038>,
or mute the thread

**Comment by Rudloff** [comment]
Thanks!
I created an F-Droid issue for this: https://gitlab.com/fdroid/rfp/issues/284

**Comment by Rudloff** [comment]
Unfortunately it seems this app can't be included in F-Droid since it uses some non-free Firebase libraries: https://gitlab.com/fdroid/rfp/issues/284#note_36467551
